---
services:
  testdb:
    image: postgres
    shm_size: 1G
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 12345
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"
    volumes:
      - .pg-data:/var/lib/postgresql/data
    networks:
      postgres_network:

networks:
  postgres_network: