spring:
  datasource:
#    url: jdbc:h2:mem:test
#    username: sa
#    password: sa
    url: jdbc:postgresql://localhost:5432/testdb
    username: test
    password: 12345

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        jdbc:
#          batch_size: 100
#        order_inserts: true
#        generate_statistics: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.stat: DEBUG
    org.hibernate: INFO